// import './instance'
// import './lifecycle'
// import './data-binding'
// import './computed'
// import './directive'
// import './compoent/define'
// import './compoent/extend'
// import './compoent/v-model'
// import './compoent/feature'
import './compoent/render'
